# 全局配置文件yaml
AppVersion:
  Backend: 1000 # 后端数据版本
  Web: 1000 # 前端内容版本

# 服务器ip，端口等内容配置
HTTPConfig:
  Ip: 127.0.0.1   # ip地址
  Port: 10   # 端口号

# 接口加密Msg参数--重要接口
CryptoConfig:
  Time: 520   # Time字段的加密参数
  Data: 1314   # Data字段的加密参数
  Jwt: StarYuhen # jwt加密参数和签名
  JwtName: StarYuhen # jwt的签署名称
  Cookie: StarYuhen # cookie和sessions加密参数
  CookieName: VocabularyLife # cookie和sessions的储存名
  CookieList: # Cookie储存的键名称列表
  - 'captcha' # 图像验证码键名

# Captcha 生成图形验证码 --(当前拥有类型数字验证码)
CaptchaConfig:
  NumberKeyLong: 6   # 生成的数字验证码的数字个数
  ImgWidth: 240   # 图形验证码的宽度
  ImgHeight: 80   # 图形验证码的长度

# mysql 数据库配置内容
MYSQLConfig:
  # 配置顺序信息  UserConfig账号-密码-数据库架构
  UserConfig:
    User: root # MYSQL的账号名
    Password: abc123456 # MYSQL的密码
    Architecture: vocabularylife  #全部转为小写 VocabularyLife
  # 指定数据库架构内的所有数据表
  UserDBTable:  # 定义数据表数组
  - 'adminaccounts'   # 用户数据表
  - 'userinfos' # 用户登录信息数据表

# redis 缓存数据库配置 --服务器外网务必必不要开放此端口
RedisConfig:
  # redis的服务器地址
  Addr: "localhost:6379"
  Password: "" # redis的数据库密码
  # redis数据库 列表
  DB:
  - 0
  - 1
  PoolSize: 100 # redis链接池，默认是4倍cpu数，这里固定 用于协程链接
  MinIdleConns: 50  #初始规定的redis，维护，让其不少于这个数

