# 全局配置文件yaml
AppVersion: 1000

# mysql 数据库配置内容
MYSQLConfig:
  # 配置顺序信息  UserConfig账号-密码-数据库架构
  UserConfig:
    User: root
    Password: abc123456
    Architecture: vocabularyife  #全部转为小写 VocabularyLife
  # 指定数据库架构内的所有数据表
  UserDBTable:  # 定义数据表数组
  - 'adminuseraccount'   # 用户数据表
