# 全局配置文件yaml
AppVersion: 1000

# 服务器ip，端口等内容配置
HTTPConfig:
  # ip地址
  Ip: 127.0.0.1
  # 端口号
  Port: 10

# 接口加密Msg参数--重要接口
CryptoConfig:
  # Time字段的加密参数
  Time: 520
  # Data字段的加密参数
  Data: 1314


# Captcha 生成图形验证码 --(当前拥有类型数字验证码)
CaptchaConfig:
# 生成的数字验证码的数字个数
  NumberKeyLong: 6
  # 图形验证码的宽度
  ImgWidth: 240
  # 图形验证码的长度
  ImgHeight: 80


# mysql 数据库配置内容
MYSQLConfig:
  # 配置顺序信息  UserConfig账号-密码-数据库架构
  UserConfig:
    User: root
    Password: abc123456
    Architecture: vocabularylife  #全部转为小写 VocabularyLife
  # 指定数据库架构内的所有数据表
  UserDBTable:  # 定义数据表数组
  - 'adminaccounts'   # 用户数据表


